# ====================================================
# SERVIDOR
# ====================================================
server.address=0.0.0.0
server.port=9000

# ====================================================
# BASE DE DATOS POSTGRESQL (usando variables .env)
# ====================================================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.properties.hibernate.default_schema=control_accesos

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


logging.level.org.postgresql=ERROR
logging.level.org.springframework.jdbc=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.scheduling=DEBUG

# ====================================================
# SECURITY / SESSION
# ====================================================
spring.security.filter.dispatcher-types=REQUEST,ASYNC,ERROR

# ====================================================
# OAUTH2 GOOGLE
# ====================================================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# ====================================================
# JWT SECRET KEY
# ====================================================
jwt.secret=${JWT_SECRET_KEY}


app.frontend.url=${FRONTEND_URL}
