spring.application.name=apizk

# PUERTO DEL SERVICIO
server.port=8080

# DATASOURCE ZK (real) 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ⚠️ NO TOCAR ESTRUCTURA
spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Evita problemas con nombres raros de tablas
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Refuerzo de solo lectura
spring.datasource.hikari.read-only=true
